services:  
  web:
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: dotnet_app
      ports:
        - "8080:8080"
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
      networks:
        - app_network
      depends_on:
      - db

  db:
    image: postgres:latest 
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=fiap
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "fiap", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
